// <auto-generated />
using System;
using AiObservatory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiObservatory.Data.Migrations
{
    [DbContext(typeof(AiObservatoryDbContext))]
    [Migration("20260704162516_AddGitHubActivity")]
    partial class AddGitHubActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiObservatory.Data.Entities.AdversarialReviewRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CostPerAcceptedFinding")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("IssuesAccepted")
                        .HasColumnType("integer");

                    b.Property<int>("IssuesRaised")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Instant>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Repo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("ReviewDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("reviewer");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("Reviewer", "Model");

                    b.HasIndex("RunId", "Reviewer", "Role")
                        .IsUnique();

                    b.ToTable("AdversarialReviewRuns", t =>
                        {
                            t.HasCheckConstraint("CK_AdversarialReviewRun_CostUsd_NonNegative", "\"CostUsd\" >= 0");

                            t.HasCheckConstraint("CK_AdversarialReviewRun_InputTokens_NonNegative", "\"InputTokens\" >= 0");

                            t.HasCheckConstraint("CK_AdversarialReviewRun_IssuesAccepted_NonNegative", "\"IssuesAccepted\" >= 0");

                            t.HasCheckConstraint("CK_AdversarialReviewRun_IssuesRaised_NonNegative", "\"IssuesRaised\" >= 0");

                            t.HasCheckConstraint("CK_AdversarialReviewRun_OutputTokens_NonNegative", "\"OutputTokens\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.BudgetRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<decimal>("ThresholdUsd")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("BudgetRules");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.CavemanSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("EstSavedTokens")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EstSavedUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Mode")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("CavemanSessions", t =>
                        {
                            t.HasCheckConstraint("CK_CavemanSession_EstSavedTokens_NonNegative", "\"EstSavedTokens\" >= 0");

                            t.HasCheckConstraint("CK_CavemanSession_EstSavedUsd_NonNegative", "\"EstSavedUsd\" >= 0");

                            t.HasCheckConstraint("CK_CavemanSession_OutputTokens_NonNegative", "\"OutputTokens\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.ClaudeActivitySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ActiveSeconds")
                        .HasColumnType("bigint");

                    b.Property<Instant>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Project");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.ToTable("ClaudeActivitySessions", t =>
                        {
                            t.HasCheckConstraint("CK_ClaudeActivitySession_ActiveSeconds_NonNegative", "\"ActiveSeconds\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.DailyAggregate", b =>
                {
                    b.Property<LocalDate>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("CacheWriteTokens")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer");

                    b.HasKey("Date", "Provider", "Model");

                    b.ToTable("DailyAggregates");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.GitHubCommit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Additions")
                        .HasColumnType("integer");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer");

                    b.Property<Instant>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("CommittedAt");

                    b.HasIndex("Repo", "Sha")
                        .IsUnique();

                    b.ToTable("GitHubCommits", t =>
                        {
                            t.HasCheckConstraint("CK_GitHubCommit_Additions_NonNegative", "\"Additions\" >= 0");

                            t.HasCheckConstraint("CK_GitHubCommit_Deletions_NonNegative", "\"Deletions\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.GitHubPullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("FirstReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("MergedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FirstReviewAt");

                    b.HasIndex("MergedAt");

                    b.HasIndex("Repo", "Number")
                        .IsUnique();

                    b.ToTable("GitHubPullRequests", t =>
                        {
                            t.HasCheckConstraint("CK_GitHubPullRequest_ReviewCount_NonNegative", "\"ReviewCount\" >= 0");
                        });
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.GitHubWorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Repo", "RunId")
                        .IsUnique();

                    b.ToTable("GitHubWorkflowRuns");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.Insight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsightType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDate>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<LocalDate>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Insights");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<LocalDate>("ActiveFrom")
                        .HasColumnType("date");

                    b.Property<LocalDate?>("ActiveTo")
                        .HasColumnType("date");

                    b.Property<int>("BillingDay")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ExtraUsageCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("AiObservatory.Data.Entities.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CacheReadTokens")
                        .HasColumnType("bigint");

                    b.Property<long?>("CacheWriteTokens")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("EventKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Provider", "EventKey")
                        .IsUnique()
                        .HasFilter("\"EventKey\" IS NOT NULL");

                    b.HasIndex("Provider", "Model")
                        .HasFilter("\"Model\" IS NOT NULL");

                    b.ToTable("UsageEvents", t =>
                        {
                            t.HasCheckConstraint("CK_UsageEvent_CacheReadTokens_NonNegative", "\"CacheReadTokens\" IS NULL OR \"CacheReadTokens\" >= 0");

                            t.HasCheckConstraint("CK_UsageEvent_CacheWriteTokens_NonNegative", "\"CacheWriteTokens\" IS NULL OR \"CacheWriteTokens\" >= 0");

                            t.HasCheckConstraint("CK_UsageEvent_CostUsd_NonNegative", "\"CostUsd\" >= 0");

                            t.HasCheckConstraint("CK_UsageEvent_InputTokens_NonNegative", "\"InputTokens\" >= 0");

                            t.HasCheckConstraint("CK_UsageEvent_OutputTokens_NonNegative", "\"OutputTokens\" >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
